### ISSUE TITLE
LegacyVpnRunner: Aborting     java.lang.IllegalStateException: racoon is dead

### ISSUE THREAD

**Issue by dydhub** [comword/DogTunnel#1]
When I tried to connect, I cannot connect，Log display:
- 04-09 13:58:25.618 1812-10088/? D/Vpn: setting state=CONNECTING, reason=execute
- 04-09 13:58:55.712 1812-10088/? I/LegacyVpnRunner: Aborting
-     java.lang.IllegalStateException: racoon is dead
-         at com.android.server.connectivity.Vpn$LegacyVpnRunner.execute(Vpn.java:1683)
-         at com.android.server.connectivity.Vpn$LegacyVpnRunner.run(Vpn.java:1562)
- 04-09 13:58:55.712 1812-10088/? D/Vpn: setting state=FAILED, reason=racoon is dead

Can you help me?

**Comment by comword** [comment]
Sorry to inform you that this repository is not being maintained. This is only a wrapper of LegacyVpn in the system, please try to add your VPN profile in the Settings and test whether it works. Racoon is an IPSec key exchange utility, but in this [mVpnService.java#L55](https://github.com/comword/DogTunnel/blob/14e0f3be59b2de1f25acca03c9c025313fc47001/app/src/main/java/org/gtdev/apps/dogtunnel/mVpnService.java#L55), hard coded plain PPTP type.

**Comment by Dyd1989** [comment]
Thank you very much for your reply. The previous question did not appear again, but it happened :
>  java.lang.IllegalStateException: KeyStore isn't unlocked
I want to create a standalone VPN client to build a pptp/L2tp connection, but Android's VpnService doesn't seem to help me. Do you have any ideas?

**Comment by dydhub** [comment]
Thank you very much for your reply.  The previous question did not appear again, but it appeared:

> java.lang.IllegalStateException: KeyStore isn't unlocked

I want to create a standalone VPN client to build a pptp/L2tp connection, but Android's VpnService doesn't seem to help me. Do you have any ideas?
